#!/bin/bash
cd /root/

#Update Upgrade
apt update
apt upgrade -y
apt install -f -y
apt autoremove -y
apt autoclean -y
#Update Upgrade

#Reboot
chmod +x /etc/rc.local
systemctl enable rc-local
echo '#!/bin/bash' > /etc/rc.local
echo 'sh /root/update.sh' >> /etc/rc.local
#Reboot
