#!/bin/bash
cd /root/

apt update
apt upgrade -y
apt install -f -y
apt autoremove -y
apt autoclean -y

wget https://github.com/tnan/virtualmin/raw/master/ubuntu20/rc.local_release-upgrade -O /etc/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local

reboot
